@url= http://localhost:8000

### POST user register
POST {{url}}/api/register
Accept: application/json
Content-Type: application/json

{
    "name" : "Leire",
    "abizena" : "Abizen",
    "dni" : "72602839G",
    "jaiotze_data" : "2004-03-27",
    "role" : "admin",
    "email" : "leire@koxme.koxme",
    "password" : "pasahitza",
    "password_confirmation" : "pasahitza"
}

### POST user login
# @name login
POST {{url}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email" : "aritz@koxme.koxme",
    "password" : "pasahitza"
}

### POST user logout
POST {{url}}/api/logout
#tokena eskuz jarri!!!!!
Authorization: Bearer 6|RtF7iQLVl5Ov437vnvOrXCmhkw5IvBkGQ5K3agHK20aa881f
Accept: application/json

### POST ekitaldiak store
POST {{url}}/api/ekitaldia
Content-Type: application/json
Accept: application/json

{
  "izena": "Ekitaldi Proba5",
  "data": "2025-05-25",
  "azalpena": "Deskribapena 5"
}

### GET ekitaldiak ikusi
GET {{url}}/api/ekitaldia
Accept: application/json

### GET ekitaldiak id=2 duena
GET {{url}}/api/ekitaldia/2

###
PUT {{url}}/api/ekitaldia/1
Content-Type: application/json
Accept: application/json

{
  "izena": "Ekitaldi Eguneratua",
  "data": "2025-03-15",
  "azalpena": "Deskribapena eguneratua"
}

###
DELETE {{url}}/api/ekitaldia/3
Accept: application/json


### Dentistak ikusi
GET {{url}}/api/dentistak
Authorization: Bearer 9|ulJy5gdddiiYAKEhQbeQiR0U4GTZnpedms4FDeH637dddaca
Accept: application/json

###
POST {{url}}/api/ekitaldiak/4/sartu
Content-Type: application/json
Accept: application/json

{
  "user_id" : "4"
}

###
GET {{url}}/api/partehartzaileak/2
Accept: application/json

###
GET {{url}}/api/ekitaldiak/2
Accept: application/json

###
POST {{url}}/api/izenaeman/5
Authorization: Bearer 9|ulJy5gdddiiYAKEhQbeQiR0U4GTZnpedms4FDeH637dddaca
Accept: application/json